// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Conditional.py'],
//   'verbosity': 30,
//   'visualise': False}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6






ufcx_finite_element element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6 =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6

// Code for element element_e607a33235f30e909bf770901503eee3709931d2

int value_shape_element_e607a33235f30e909bf770901503eee3709931d2[1] = { 2 };
int reference_value_shape_element_e607a33235f30e909bf770901503eee3709931d2[1] = { 2 };
ufcx_finite_element* sub_elements_element_e607a33235f30e909bf770901503eee3709931d2[2] = { &element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6, &element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6 };


ufcx_finite_element element_e607a33235f30e909bf770901503eee3709931d2 =
{
  .signature = "VectorElement(Basix element (P, triangle, 1, gll_warped, unset, False), 2)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_e607a33235f30e909bf770901503eee3709931d2,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_e607a33235f30e909bf770901503eee3709931d2,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_e607a33235f30e909bf770901503eee3709931d2,
  .custom_element = NULL
};

// End of code for element element_e607a33235f30e909bf770901503eee3709931d2

// Code for element element_581fed46384b0aa58851a69fa0b956a0c02a1cca






ufcx_finite_element element_581fed46384b0aa58851a69fa0b956a0c02a1cca =
{
  .signature = "Basix element (P, triangle, 2, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_581fed46384b0aa58851a69fa0b956a0c02a1cca

// Code for dofmap dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6



void tabulate_entity_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6[4] = { 1, 2, 3, 0 };

ufcx_dofmap dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6

// Code for dofmap dofmap_e607a33235f30e909bf770901503eee3709931d2

ufcx_dofmap* sub_dofmaps_dofmap_e607a33235f30e909bf770901503eee3709931d2[2] = { &dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6, &dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6 };

void tabulate_entity_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2[4] = { 1, 2, 3, 0 };

ufcx_dofmap dofmap_e607a33235f30e909bf770901503eee3709931d2 =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, triangle, 1, gll_warped, unset, False), 2)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .num_entity_dofs = num_entity_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_e607a33235f30e909bf770901503eee3709931d2,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_e607a33235f30e909bf770901503eee3709931d2
};

// End of code for dofmap dofmap_e607a33235f30e909bf770901503eee3709931d2

// Code for dofmap dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca



void tabulate_entity_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 3;
    break;
  case 1:
    dofs[0] = 4;
    break;
  case 2:
    dofs[0] = 5;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 1;
    dofs[1] = 2;
    dofs[2] = 3;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 4;
    break;
  case 2:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 5;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca[4] = { 1, 1, 0, 0 };

int num_entity_closure_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca[4] = { 1, 3, 6, 0 };

ufcx_dofmap dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 2, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 6,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca

// Code for integral integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8

void tabulate_tensor_integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_48e[3] = { 0.1666666666666667, 0.1666666666666667, 0.1666666666666667 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE6_C0_D10_Q48e[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
  static const double FE6_C1_D01_Q48e[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
  static const double FE6_C1_Q48e[1][1][3][3] =
    { { { { 0.6666666666666666, 0.1666666666666666, 0.1666666666666667 },
          { 0.1666666666666667, 0.1666666666666666, 0.6666666666666665 },
          { 0.1666666666666667, 0.6666666666666665, 0.1666666666666667 } } } };
  static const double FE7_C0_Q48e[1][1][3][6] =
    { { { { 0.2222222222222222, -0.1111111111111112, -0.1111111111111111, 0.1111111111111111, 0.4444444444444443, 0.4444444444444444 },
          { -0.1111111111111112, -0.111111111111111, 0.2222222222222222, 0.4444444444444445, 0.4444444444444447, 0.1111111111111112 },
          { -0.1111111111111112, 0.2222222222222222, -0.1111111111111111, 0.4444444444444443, 0.1111111111111111, 0.4444444444444445 } } } };
  // Quadrature loop independent computations for quadrature rule 48e
  double J_c0 = 0.0;
  double J_c3 = 0.0;
  double J_c1 = 0.0;
  double J_c2 = 0.0;
  for (int ic = 0; ic < 3; ++ic)
  {
    J_c0 += coordinate_dofs[ic * 3] * FE6_C0_D10_Q48e[0][0][0][ic];
    J_c3 += coordinate_dofs[ic * 3 + 1] * FE6_C1_D01_Q48e[0][0][0][ic];
    J_c1 += coordinate_dofs[ic * 3] * FE6_C1_D01_Q48e[0][0][0][ic];
    J_c2 += coordinate_dofs[ic * 3 + 1] * FE6_C0_D10_Q48e[0][0][0][ic];
  }
  double sp_48e[5];
  sp_48e[0] = (1 > 0.0 ? c[0] : 1 + c[0]);
  sp_48e[1] = J_c0 * J_c3;
  sp_48e[2] = J_c1 * J_c2;
  sp_48e[3] = sp_48e[1] + -1 * sp_48e[2];
  sp_48e[4] = fabs(sp_48e[3]);
  for (int iq = 0; iq < 3; ++iq)
  {
    // Quadrature loop body setup for quadrature rule 48e
    // Varying computations for quadrature rule 48e
    double x_c1 = 0.0;
    double x_c0 = 0.0;
    for (int ic = 0; ic < 3; ++ic)
    {
      x_c1 += coordinate_dofs[ic * 3 + 1] * FE6_C1_Q48e[0][0][iq][ic];
      x_c0 += coordinate_dofs[ic * 3] * FE6_C1_Q48e[0][0][iq][ic];
    }
    double sv_48e[4];
    sv_48e[0] = x_c1 + -1 * x_c0;
    sv_48e[1] = (0.55 + (-0.05 + sv_48e[0]) >= 0.0 && ((x_c0 >= 0.55 && x_c0 <= 0.95) && !(x_c1 < 0.05 || x_c1 > 0.45)) ? -1.0 : 0.0) + (pow(-0.33 + x_c0, 2) + pow(-0.67 + x_c1, 2) <= 0.025 ? (pow(-0.33 + x_c0, 2) + pow(-0.67 + x_c1, 2) <= 0.015 ? -1.0 : 5.0) : 0.0);
    sv_48e[2] = sv_48e[1] + sp_48e[0];
    sv_48e[3] = sv_48e[2] * sp_48e[4];
    const double fw0 = sv_48e[3] * weights_48e[iq];
    for (int i = 0; i < 6; ++i)
      A[i] += fw0 * FE7_C0_Q48e[0][0][iq][i];
  }
}



ufcx_integral integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8,
  .needs_facet_permutations = false,
  .coordinate_element = &element_e607a33235f30e909bf770901503eee3709931d2,
};

// End of code for integral integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8

// Code for form form_a711df029bdc97d24bd9d21cc175815f382d858e


ufcx_dofmap* dofmaps_form_a711df029bdc97d24bd9d21cc175815f382d858e[1] = { &dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca };
ufcx_finite_element* finite_elements_form_a711df029bdc97d24bd9d21cc175815f382d858e[1] = { &element_581fed46384b0aa58851a69fa0b956a0c02a1cca };

// Return a list of the coefficient names.
const char** coefficient_name_form_a711df029bdc97d24bd9d21cc175815f382d858e(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_a711df029bdc97d24bd9d21cc175815f382d858e(void)
{
static const char* names[1] = { "g" };
return names;
}

int* integral_ids_form_a711df029bdc97d24bd9d21cc175815f382d858e(ufcx_integral_type integral_type)
{
static int integral_ids_cell_form_a711df029bdc97d24bd9d21cc175815f382d858e[1] = { -1 };
switch (integral_type)
{
case cell:
  return integral_ids_cell_form_a711df029bdc97d24bd9d21cc175815f382d858e;
default:
  return NULL;
}
}

int num_integrals_form_a711df029bdc97d24bd9d21cc175815f382d858e(ufcx_integral_type integral_type)
{
switch (integral_type)
{
case cell:
  return 1;
case interior_facet:
  return 0;
case exterior_facet:
  return 0;
default:
  return 0;
}
}

ufcx_integral** integrals_form_a711df029bdc97d24bd9d21cc175815f382d858e(ufcx_integral_type integral_type)
{
static ufcx_integral* integrals_cell_form_a711df029bdc97d24bd9d21cc175815f382d858e[1] = { &integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8 };
switch (integral_type)
{
case cell:
  return integrals_cell_form_a711df029bdc97d24bd9d21cc175815f382d858e;
default:
  return NULL;
}
}

ufcx_form form_a711df029bdc97d24bd9d21cc175815f382d858e =
{

  .signature = "b616c30971158c364fcadfa0de3537c41ebb4143a1fbf408d0c461d06943680d5a7ac904a09152bdebf7191aebdab8e96ea2ef4adb6f2c4f935d87c74af169cd",
  .rank = 1,
  .num_coefficients = 0,
  .num_constants = 1,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_a711df029bdc97d24bd9d21cc175815f382d858e,
  .constant_name_map = constant_name_form_a711df029bdc97d24bd9d21cc175815f382d858e,

  .finite_elements = finite_elements_form_a711df029bdc97d24bd9d21cc175815f382d858e,
  .dofmaps = dofmaps_form_a711df029bdc97d24bd9d21cc175815f382d858e,

  .integral_ids = integral_ids_form_a711df029bdc97d24bd9d21cc175815f382d858e,
  .num_integrals = num_integrals_form_a711df029bdc97d24bd9d21cc175815f382d858e,

  .integrals = integrals_form_a711df029bdc97d24bd9d21cc175815f382d858e
};

// Alias name
ufcx_form* form_Conditional_L = &form_a711df029bdc97d24bd9d21cc175815f382d858e;

ufcx_function_space* functionspace_form_Conditional_L(const char* function_name)
{
static ufcx_function_space functionspace_v =
{
.finite_element = &element_581fed46384b0aa58851a69fa0b956a0c02a1cca,
.dofmap = &dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 1
};
if (strcmp(function_name, "v") == 0)
  return &functionspace_v;
return NULL;

}

// End of code for form form_a711df029bdc97d24bd9d21cc175815f382d858e
