// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['Conditional.py'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_finite_element element_610068d4f9250b8b2ec11740d6828a72a0a8aaf6;

extern ufcx_finite_element element_e607a33235f30e909bf770901503eee3709931d2;

extern ufcx_finite_element element_581fed46384b0aa58851a69fa0b956a0c02a1cca;

extern ufcx_dofmap dofmap_610068d4f9250b8b2ec11740d6828a72a0a8aaf6;

extern ufcx_dofmap dofmap_e607a33235f30e909bf770901503eee3709931d2;

extern ufcx_dofmap dofmap_581fed46384b0aa58851a69fa0b956a0c02a1cca;

extern ufcx_integral integral_fbdd47f66febfd432c1d23174aa7bed7780fbde8;

extern ufcx_form form_a711df029bdc97d24bd9d21cc175815f382d858e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_Conditional_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufcx_function_space* functionspace_form_Conditional_L(const char* function_name);

#ifdef __cplusplus
}
#endif
